version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db_clientes
    ports:
      - "5432:5432"
    volumes:
      - ./app/sql/estrutura.sql:/docker-entrypoint-initdb.d/estrutura.sql
      - processo_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready --username=postgres --dbname=db_clientes'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/postgres
    volumes:
      - ./app:/app/app
    command: python app/main.py

volumes:
  processo_postgres_data:

networks:
  default:
    driver: bridge
